name: Build

permissions:
  contents: write

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATA_PATH: /opt/data
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clone lexicon repo
        uses: actions/checkout@v4
        with:
          repository: domino14/word-game-lexica
          path: word-game-lexica
          token: ${{ secrets.LEXICA_GH_PAT }}

      - run: mv $GITHUB_WORKSPACE/word-game-lexica /opt/word-game-lexica
      - run: cp -r data /opt/data
      - run: mkdir -p /opt/data/lexica/gaddag
      - run: mv /opt/word-game-lexica/gaddag/*.kwg /opt/data/lexica/gaddag

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.22"

      - name: Run tests
        run: go test $(go list ./... | grep -v wasm)
